### ISSUE TITLE
Incorrect Cyrulik text in the data-description field (solution proposed)

### ISSUE THREAD

**Issue by semteacher** [sebsoftnl/moodle-enrol_gwpayments#16]
When course name is in Cyrulik it has been placed into the template's "data-description" in incorrect representation - as codes of chars:
![image](https://github.com/sebsoftnl/moodle-enrol_gwpayments/assets/1571998/ca3defd3-c7e4-4381-9e11-ec74c1bd3019)
It leads to incorrect representation of items in the payment system processing
![image](https://github.com/sebsoftnl/moodle-enrol_gwpayments/assets/1571998/a177a667-c7de-4272-8f3f-8c987a46f857)

To solve this issue, the following line in the `"payment_region.mustache"` template file 
`data-description="{{# quote }}"{{description}}{{/ quote }}`
must be changed to
`data-description="{{description}}"`

Results:
![image](https://github.com/sebsoftnl/moodle-enrol_gwpayments/assets/1571998/36038765-329e-41fa-88d6-d70d83bccf24)

**Comment by rogiervandongen** [comment]
@semteacher 
Thanks for noticing. I might implement another method due to the fact quotes could be present in the data-description, hence the {{#quote}}.

**Comment by rogiervandongen** [comment]
@semteacher 
Yes, I've made progress and will be pushing soon.

Your suggestion will have been implemented, albeit with a small addition: the main description will be stripped from ALL single and double quotes. There's no real other route I can follow because I cannot touch the internals of Moodle's implementation which makes use of the description. This means I can't, for example, encode the descriptor (for instance, as base64 encoded data).

So as long as no single or double quotes are used in the course name, you should be alright :)

**Comment by rogiervandongen** [comment]
Closing as this was fixed in v4.3.3 (github never auto-closed this issue).
