### ISSUE TITLE
problem installation for moodle 4.4 version

### ISSUE THREAD

**Issue by skandercci** [sebsoftnl/moodle-enrol_gwpayments#22]
i can't install this plugin for moodle version 4.4

you find here the image capture when i try to install it

hope will give me solution or update the plugin to support 4.4 moodle version
thank you very much

![p e p](https://github.com/user-attachments/assets/3b64e959-c603-4030-bde7-03fb90549ac0)

**Comment by rogiervandongen** [comment]
@skandercci 
I'm not sure what happens here, because the screenshot implies you were performing an upgrade of a known plugin (becoming clear due to the "Upgrading to new version" heading).

I've tested a fresh installation of the plugin (1.1.0 (build 2024090100)) on a following Moodle: Moodle 4.4.3+ (Build: 20240924)
The install completes without errors.

Just as a failsafe, I've then uninstalled.
Now installed the first release (1.0.5 (build 2021081605)) -> installs correctly.
Upgrade to latest release (1.1.0 (build 2024090100)) -> upgrades correctly.

I'm suspecting your problems are beyond my assistence (any time I've encountered any issue such as described, someone modified the database or some other form of corruption had occured. This may not be due to human intervention but for example due to PHP timeouts. Aka: PHP throws a timeout before the complete plugin was installed, but database tables _were_ in fact already added).
